// <auto-generated />
using System;
using LogsPlatform.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogsPlatform.Infrastructure.Migrations
{
    [DbContext(typeof(LogsPlatformDbContext))]
    [Migration("20260818141413_AddProcessNodeAndOperation")]
    partial class AddProcessNodeAndOperation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LogsPlatform.Domain.Entities.AppEnvironment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<bool>("IsProduction")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "Name")
                        .IsUnique();

                    b.ToTable("AppEnvironments");
                });

            modelBuilder.Entity("LogsPlatform.Domain.Entities.AppModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "Name")
                        .IsUnique();

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("LogsPlatform.Domain.Entities.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("LogsPlatform.Domain.Entities.Operation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProcessId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProcessId", "Name")
                        .IsUnique();

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("LogsPlatform.Domain.Entities.ProcessNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ScreenServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScreenServiceId", "Name")
                        .IsUnique();

                    b.ToTable("Processes");
                });

            modelBuilder.Entity("LogsPlatform.Domain.Entities.ScreenService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId", "Name")
                        .IsUnique();

                    b.ToTable("ScreenServices");
                });

            modelBuilder.Entity("LogsPlatform.Domain.Entities.AppEnvironment", b =>
                {
                    b.HasOne("LogsPlatform.Domain.Entities.Application", "Application")
                        .WithMany("Environments")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("LogsPlatform.Domain.Entities.AppModule", b =>
                {
                    b.HasOne("LogsPlatform.Domain.Entities.Application", "Application")
                        .WithMany("Modules")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("LogsPlatform.Domain.Entities.Operation", b =>
                {
                    b.HasOne("LogsPlatform.Domain.Entities.ProcessNode", "Process")
                        .WithMany("Operations")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Process");
                });

            modelBuilder.Entity("LogsPlatform.Domain.Entities.ProcessNode", b =>
                {
                    b.HasOne("LogsPlatform.Domain.Entities.ScreenService", "ScreenService")
                        .WithMany("Processes")
                        .HasForeignKey("ScreenServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScreenService");
                });

            modelBuilder.Entity("LogsPlatform.Domain.Entities.ScreenService", b =>
                {
                    b.HasOne("LogsPlatform.Domain.Entities.AppModule", "Module")
                        .WithMany("ScreenServices")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("LogsPlatform.Domain.Entities.AppModule", b =>
                {
                    b.Navigation("ScreenServices");
                });

            modelBuilder.Entity("LogsPlatform.Domain.Entities.Application", b =>
                {
                    b.Navigation("Environments");

                    b.Navigation("Modules");
                });

            modelBuilder.Entity("LogsPlatform.Domain.Entities.ProcessNode", b =>
                {
                    b.Navigation("Operations");
                });

            modelBuilder.Entity("LogsPlatform.Domain.Entities.ScreenService", b =>
                {
                    b.Navigation("Processes");
                });
#pragma warning restore 612, 618
        }
    }
}
